version: '3'
services:
  translate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
